# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Akshay Bansal"
title:              "Hey! Welcome to my personal site!"
description:        "I am a PhD candidate at Virginia Tech working on quantum information science and cryptography."


# URL
url:                http://kordinglab.com
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  # - name:           "people"
  #   href:           "/people"
  # - name:           "blog"
  #   href:           "/blog"
  - name:           "cv"
    href:           "/documents/RDL_CV_20F.pdf"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
